spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kkgames?useSSL=false&serverTimezone=CET
    username: kkgames
    password: kkgames123
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://mysqldb:3306/kkgames?useSSL=false&serverTimezone=CET&useSSL=false&allowPublicKeyRetrieval=true